In [1]:
from numpy import *
from scipy.sparse import *

In [2]:
playlistsWithTracksRepeated=genfromtxt("train_final.csv", skip_header=1, dtype=int32)
playlistsWithTracksRepeated

array([[ 3271849,  2801526],
       [ 5616275,   727878],
       [11267488,  2805283],
       ..., 
       [ 2659739,  1468602],
       [10687820,  1187581],
       [ 4962329,  1094523]])

In [3]:
playlistsWithTracksRepeated.shape

(1040522, 2)

In [4]:
playlistsRepeated=playlistsWithTracksRepeated[:,0]
playlistsRepeated

array([ 3271849,  5616275, 11267488, ...,  2659739, 10687820,  4962329])

In [5]:
tracks=playlistsWithTracksRepeated[:,1]
tracks

array([2801526,  727878, 2805283, ..., 1468602, 1187581, 1094523])

In [6]:
playListsUnique,counts=unique(playlistsWithTracksRepeated[:,0],return_counts=True)
playListsUnique,playListsUnique.size

(array([    7569,     7614,     7641, ..., 11765405, 11766293, 11766362]),
 45649)

In [7]:
counts

array([ 9, 11,  8, ...,  6,  1, 13], dtype=int64)

In [8]:
maxSize=max(counts)
maxSize

199

In [9]:
allP=[]
for p in playListsUnique:
    thisTracks=[p]#it contains also the playlist ID
    for i in where(playlistsRepeated==p)[0]:
        thisTracks.append(tracks[i])
    for i in range(maxSize-len(thisTracks)+1):
        thisTracks.append(0)
    allP.append(thisTracks)

KeyboardInterrupt: 

In [ ]:
arrAllP=array([x for x in allP])

In [ ]:
arrAllP

In [ ]:
save_npz("all_playlists_with_tracks.npz",csc_matrix(arrAllP))

In [ ]:
all_playlists_with_tracks=load_npz("all_playlists_with_tracks.npz")

In [6]:
all_playlists_with_tracks

<45649x200 sparse matrix of type '<class 'numpy.int64'>'
	with 1086171 stored elements in Compressed Sparse Column format>

In [5]:
tracks_with_tags=load("tracks_with_tags.npy")
tracks_with_tags

array([[2972914,   54087,    1757,    1718,  116712,  189631],
       [2750239,  189631,    3424,  177424,   46208,  205245],
       [1550729,   54087,  109806,   46869,  183258,   54337],
       ..., 
       [2584455,       0,       0,       0,       0,       0],
       [2299706,       0,       0,       0,       0,       0],
       [2739985,       0,       0,       0,       0,       0]], dtype=int32)

In [7]:
pIDs=all_playlists_with_tracks[:,0]
pIDs

<45649x1 sparse matrix of type '<class 'numpy.int64'>'
	with 45649 stored elements in Compressed Sparse Column format>

In [10]:
pTracks=all_playlists_with_tracks[:,1:]
pTracks

<45649x199 sparse matrix of type '<class 'numpy.int64'>'
	with 1040522 stored elements in Compressed Sparse Column format>

In [28]:
tIDs=tracks_with_tags[:,0]
tIDs

array([2972914, 2750239, 1550729, ..., 2584455, 2299706, 2739985], dtype=int32)

In [9]:
tTags=tracks_with_tags[:,1:]
tTags

array([[ 54087,   1757,   1718, 116712, 189631],
       [189631,   3424, 177424,  46208, 205245],
       [ 54087, 109806,  46869, 183258,  54337],
       ..., 
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0]], dtype=int32)

In [ ]:
"""
A=lil_matrix((10000,maxSize))
for x,tracks in enumerate(tracklist_by_playlist):
    tracks=trim_zeros(tracks)
    alltags=[]
    for t in tracks:
        tags = tag_indexed_byidtrack[t]
        alltags+=list(tags)
    tagsArray=(array(alltags)).astype(int)
    tagsCount=bincount(tagsArray)#posizione = tagID, contenuto = conteggio di quel tag
    tagsCount[0]=0#altrimenti venivano contati anche gli zeri
    tagsCount=resize(tagsCount,(maxSize,))
    A[x]=tagsCount
"""

In [123]:
allT=[]
for tracks in pTracks:
    thisTags=[]
    for t in tracks.data:
        i=where(tIDs==t)[0]
        if (i.size!=0):
            i=i[0]
            thisTags+=list(tTags[i])
    allT.append(thisTags)

In [128]:
len(allT)

45649

In [161]:
highestTag=max([max(x) for x in allT])
maxSize3=highestTag+1
maxSize3

276615

In [162]:
arrAllT=lil_matrix((45649,maxSize3))
for i,tags in enumerate(allT):
    arrAllT[i]=bincount(tags,minlength=maxSize3)

In [164]:
arrAllT

<45649x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 1813599 stored elements in LInked List format>

In [165]:
save_npz("all_playlists_with_tags.npz",csc_matrix(arrAllT))