In [1]:
from numpy import *
from scipy import *
from scipy.sparse import *
from scipy.spatial.distance import *
from sklearn.preprocessing import *

In [11]:
def my_func(a):
    return (a[0]+a[-1])*0.5

In [17]:
l=[[3,2,1],[4,5,6],[7,8,9]]
b=array(l)
b

array([[3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
apply_along_axis(my_func,0,b)

array([ 5.,  5.,  5.])

In [19]:
apply_along_axis(my_func,1,b)

array([ 2.,  5.,  8.])

In [25]:
apply_along_axis(sorted,1,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
apply_along_axis(sum,0,b)

array([14, 15, 16])

In [27]:
apply_along_axis(sum,1,b)

array([ 6, 15, 24])

In [31]:
apply_over_axes(sum,b,[0,1])

array([[45]])

In [33]:
c=array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [36]:
cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [45]:
d=array([1,2,3,4,6,7])
d

array([1, 2, 3, 4, 6, 7])

In [47]:
cosine(c,d)

0.0029187363384267639

In [65]:
"""
0=uguali
1=perpendicolari
2=opposti
"""
cosine(array([0,0,0,1]),array([0,0,0,1]))

0.0

In [2]:
highestTag=276614 # trovato ciclando sui tag
maxSize=highestTag+1

In [3]:
tracks_with_tags=load("tracks_with_tags.npy")
tracks_with_tags

array([[2972914,   54087,    1757,    1718,  116712,  189631],
       [2750239,  189631,    3424,  177424,   46208,  205245],
       [1550729,   54087,  109806,   46869,  183258,   54337],
       ..., 
       [2584455,       0,       0,       0,       0,       0],
       [2299706,       0,       0,       0,       0,       0],
       [2739985,       0,       0,       0,       0,       0]], dtype=int32)

In [4]:
only_tTags=tracks_with_tags[:,1:]
only_tTags

array([[ 54087,   1757,   1718, 116712, 189631],
       [189631,   3424, 177424,  46208, 205245],
       [ 54087, 109806,  46869, 183258,  54337],
       ..., 
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0]], dtype=int32)

In [74]:
only_tTags.shape

(100000, 5)

In [78]:
B=lil_matrix((100000,maxSize))
for i,tags in enumerate(only_tTags):
    B[i]=bincount(tags, minlength=maxSize)

In [80]:
B

<100000x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 487328 stored elements in LInked List format>

In [92]:
B[0]

<1x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in LInked List format>

In [94]:
B_csc=csc_matrix(B)

In [95]:
B_csc

<100000x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 487328 stored elements in Compressed Sparse Column format>

In [101]:
save_npz("tracks_with_tags_bincount.npz",B_csc)

In [84]:
B[0].data

array([list([1.0, 1.0, 1.0, 1.0, 1.0])], dtype=object)

In [5]:
playlists_with_tags=load_npz("playlists_with_tags.npz")
playlists_with_tags

<10000x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 559049 stored elements in Compressed Sparse Column format>

In [113]:
playlists_with_tags[0]

<1x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 66 stored elements in Compressed Sparse Column format>

In [111]:
squeeze(B_csc[0])

array(<1x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Column format>, dtype=object)

In [121]:
%timeit -n 1000 cosine(playlists_with_tags[0].toarray(),B_csc[0].toarray())

1000 loops, best of 3: 7.96 ms per loop


In [173]:
cosine(playlists_with_tags[0].toarray(),B_csc[7].toarray())

0.69859911937339858

In [122]:
%timeit -n 1000 cosine(playlists_with_tags[0].todense(),B_csc[0].todense())

1000 loops, best of 3: 8.02 ms per loop


In [125]:
cosine(playlists_with_tags[0].todense(),B_csc[0].todense())

0.9513869547376449

In [160]:
cosine(array([0,1,1,1]),array([1,1,1,1]))

0.13397459621556129

In [433]:
a=array([0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1])
b=array([0,1,100,100,0,0,0,1,5,1,0,0,9,0,0,0,0,0,0,0,2])
bavg=mean(b)
#b[b!=0]=b-bavg

In [198]:
a=array([0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1])
b=array([0,0,0,0,0,0,0,1,0,0,0,100,100,0,100,0,0,0,0,0,1])
bavg=mean(b)
b=b-bavg
cosine(a,b)

1.1979570350642994

In [199]:
a=array([0,0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1])
b=array([0,0,1,1,0,1,0,0,1,0,200,0,0,200,0,0,200,0,0,0,1])
bavg=mean(b)
b=b-bavg
cosine(a,b)

1.1941588932214173

In [250]:
type(B_csc[0])

scipy.sparse.csc.csc_matrix

In [251]:
type(playlists_with_tags[0])

scipy.sparse.csc.csc_matrix

In [271]:
samplePlaylistNormalized=normalize(playlists_with_tags[9])

In [284]:
B_csc[10].nonzero()[1]

array([  3982,  11056,  81223, 189631, 205245], dtype=int32)

In [327]:
B_csc[18].nonzero()[1]

array([   404,   3668,  46208, 189631, 205245], dtype=int32)

In [328]:
sampleSongA=B_csc[10]
sampleSongB=B_csc[18]
cosine(sampleSongA.todense(),sampleSongB.todense())

0.60000000000000009

In [351]:
songTagNorm=B_csc[10]
samplePlist=playlists_with_tags[0]
playTagNorm=normalize(samplePlist)
print(intersect1d(songTagNorm.nonzero()[1],samplePlist.nonzero()[1]))
cosine(songTagNorm.todense(),playTagNorm.todense())

[  3982  11056  81223 189631 205245]


0.64998607411104348

In [398]:
testM=coo_matrix([["t1p1","t2p1","t3p1"],["t1p2","t2p2","t3p2"],["t1p3","t2p3","t3p3"],["t1p4","t2p4","t3p4"]])
testS=coo_matrix([["t1s1","t2s1"],["t1S2","t2s2"],["t1s3","t2s3"]])

for r,c,d in zip(testM.row,testM.col,testM.data):
    print(r,c,d)
    for rs,cs,ds in zip(testS.row,testS.col,testS.data):
        #print("  ",rs,cs,ds)

SyntaxError: unexpected EOF while parsing (<ipython-input-398-c74940fd95a7>, line 7)

In [6]:
orderedIndexes=load("indexsortedDESCENDENT.npy")
orderedIndexes

array([43529, 94738, 57501, ..., 17820, 79618, 43000])

In [413]:
C=lil_matrix((100000,maxSize))
for i,t in enumerate(orderedIndexes):
    C[i]=bincount(only_tTags[t], minlength=maxSize)

In [418]:
C

<100000x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 487328 stored elements in LInked List format>

In [424]:
C[0].nonzero()[1]

array([ 43212,  64978,  70618,  70625, 255208], dtype=int32)

In [416]:
B_csr=csr_matrix(B)

In [417]:
# BAD, using unordered tracks
p=normalize(playlists_with_tags[0]).toarray()
minDists=[1,1,1,1,1]
idTs=[0,0,0,0,0]
for idT,t in enumerate(B_csr):
    dist=cosine(p,t.toarray())
    myMax=max(minDists)
    if (dist<myMax):
        toReplace=minDists.index(myMax)
        minDists[toReplace]=dist
        idTs[toReplace]=tracks_with_tags[idT][0]

KeyboardInterrupt: 

In [405]:
minDists,idTs

([0.11524257622513767,
  0.11524257622513767,
  0.11524257622513767,
  0.11524257622513767,
  0.11524257622513767],
 [3361580, 2293423, 1344333, 3080844, 1354906])

In [426]:
C_csc=csc_matrix(C)

In [430]:
save_npz("tracks_with_tags_bincount_ordered.npz",C_csc)

In [19]:
C=load_npz("tracks_with_tags_bincount_ordered.npz")

In [21]:
type(C)

scipy.sparse.csc.csc_matrix

In [35]:
C.getcol(44)

<100000x1 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Column format>

In [9]:
# prova con 1 playlist
p=normalize(playlists_with_tags[2]).toarray()
minDists=[1,1,1,1,1]
idTs=[0,0,0,0,0]
for indT,t in zip(orderedIndexes,C):
    dist=cosine(p,t.toarray())
    myMax=max(minDists)
    if (dist<myMax):
        toReplace=minDists.index(myMax)
        minDists[toReplace]=dist
        idTs[toReplace]=tracks_with_tags[indT][0]

In [42]:
# prova con 1 playlist reduced
p=normalize(reducedP[0]).toarray()
minDists=[1,1,1,1,1]
idTs=[0,0,0,0,0]
for indT,t in zip(orderedIndexes,reducedT):
    dist=cosine(p,t.toarray())
    myMax=max(minDists)
    if (dist<myMax):
        toReplace=minDists.index(myMax)
        minDists[toReplace]=dist
        idTs[toReplace]=tracks_with_tags[indT][0]

/home/oppy/.local/lib/python3.5/site-packages/scipy/spatial/distance.py:505: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - np.dot(u, v) / (norm(u) * norm(v))


In [43]:
minDists,idTs

([0.1149810998994909,
  0.1149810998994909,
  0.1149810998994909,
  0.1149810998994909,
  0.1149810998994909],
 [2730084, 2644788, 1539357, 897771, 1174456])

In [36]:
pIDs=genfromtxt("target_playlists.csv",skip_header=1, dtype=int32)
pIDs[0],pIDs[1]

(10024884, 10624787)

In [38]:
reducedP=load_npz("playlist_reduced.npz")

In [39]:
reducedT=load_npz("tracks_ordered_tags_reduced.npz")

In [44]:
def cleanString(pID,tIDs):
    myStr=""
    myStr+=str(pID)
    myStr+=","
    for t in tIDs:
        myStr+=" "
        myStr+= str(t)
    myStr+="\n"
    return myStr

In [46]:
cleanString(pIDs[0],idTs)

'10024884, 2730084 2644788 1539357 897771 1174456\n'

In [50]:
#prova infinita sulle 100k
with open("personalized_tags6.csv","a") as myfile:
    for i,idP in enumerate(pIDs):
        p=normalize(reducedP[i]).toarray()
        minDists=[1,1,1,1,1]
        idTs=[0,0,0,0,0]
        for indT,t in zip(orderedIndexes,reducedT):
            dist=cosine(p,t.toarray())
            myMax=max(minDists)
            if (dist<myMax):
                toReplace=minDists.index(myMax)
                minDists[toReplace]=dist
                idTs[toReplace]=tracks_with_tags[indT][0]
        myfile.write(cleanString(idP,idTs))

/home/oppy/.local/lib/python3.5/site-packages/scipy/spatial/distance.py:505: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - np.dot(u, v) / (norm(u) * norm(v))


KeyboardInterrupt: 

In [51]:
reducedTargetT=load_npz("reducedTargetT.npz")

In [54]:
reducedTargetT.shape

(32195, 31900)

In [56]:
orderedTargetIndexes=load("orderedTargetIndexes.npy")

In [57]:
orderedTargetIndexes.size

32195

In [58]:
#prova infinita sulle 30k target
with open("personalized_tags7.csv","a") as myfile:
    for i,idP in enumerate(pIDs):
        if (i<=437):#arrivato alla 4639524
            continue
        else:
            p=normalize(reducedP[i]).toarray()
            minDists=[1,1,1,1,1]
            idTs=[0,0,0,0,0]
            for indT,t in zip(orderedTargetIndexes,reducedTargetT):
                dist=cosine(p,t.toarray())
                myMax=max(minDists)
                if (dist<myMax):
                    toReplace=minDists.index(myMax)
                    minDists[toReplace]=dist
                    idTs[toReplace]=tracks_with_tags[indT][0]
            myfile.write(cleanString(idP,idTs))

/home/oppy/.local/lib/python3.5/site-packages/scipy/spatial/distance.py:505: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - np.dot(u, v) / (norm(u) * norm(v))


KeyboardInterrupt: 

In [ ]:
#topNTarget=[1563309, 1363985, 3705881, 1595978, 3166665]