In [1]:
from numpy import *
from scipy.sparse import *

In [5]:
uniqueArtists=load("uniqueArtists_NeededToIndexThe_ArtistReducedMatrices.npy")
uniqueArtists,uniqueArtists.size

(array([    78,    109,    144, ..., 567363, 568165, 570588], dtype=int32),
 17536)

In [13]:
trackArtist=load("track_artist.npy")
trackArtist,trackArtist.shape

(array([[2972914,     144],
        [2750239,     246],
        [1550729,     144],
        ..., 
        [2584455,   27938],
        [2299706,  373892],
        [2739985,  567363]], dtype=int32), (100000, 2))

In [30]:
artistsRepeated=trackArtist[:,1]
onlyTracks=trackArtist[:,0]

In [35]:
artistTrack=[]
for a in uniqueArtists:
    thisTracks=[]
    indexes=where(artistsRepeated==a)[0]
    for i in indexes:
        thisTracks.append(onlyTracks[i])
    artistTrack.append(thisTracks)

In [54]:
len(artistTrack),artistTrack[-3],uniqueArtists[-3]
#ok it works

(17536, [896846, 2739985], 567363)

In [75]:
orderedTracks=load("ordered_tracks.npy").astype(int32)
orderedTracks

array([1563309, 1363985, 3705881, ..., 2005630, 4432895, 3626362], dtype=int32)

In [94]:
artistTrack[0]

[396560, 567332, 465094, 475505, 1723620, 3557465, 715551]

In [91]:
for a in artistTrack:
    a.sort(key=lambda x : where(orderedTracks==x))

In [96]:
len(artistTrack)

17536

In [104]:
maxSize=max([len(a) for a in artistTrack])
maxSize

221

In [105]:
min([len(a) for a in artistTrack])

1

In [107]:
for a in artistTrack:
    a+=[0]*(maxSize-len(a))

In [108]:
max([len(a) for a in artistTrack])

221

In [109]:
min([len(a) for a in artistTrack])

221

In [112]:
artistTrackSparse=csc_matrix(artistTrack)
artistTrackSparse

<17536x221 sparse matrix of type '<class 'numpy.int64'>'
	with 100000 stored elements in Compressed Sparse Column format>

In [120]:
save_npz("artists_with_tracksID_ordered_by_occurrencies.npz",artistTrackSparse)