In [1]:
from numpy import *
from scipy.sparse import *

In [3]:
nonSparsePlaylistArtist=load_npz("all_playlists_with_artist.npz")
nonSparsePlaylistArtist

<45649x199 sparse matrix of type '<class 'numpy.int64'>'
	with 1040522 stored elements in Compressed Sparse Column format>

In [16]:
artistIDs=load("fucking_ordered_artists.npy")
artistIDs

array([    78,    109,    144, ..., 567363, 568165, 570588], dtype=int32)

In [17]:
artistIDs.size

17536

In [10]:
a1=nonSparsePlaylistArtist[0].data
a1

array([ 20683, 281045,  22096, 281045, 319024, 319024, 449220,  54765,
        53362])

In [30]:
searchsorted(artistIDs,a1)

array([  646, 10548,   723, 10548, 11937, 11937, 16741,  2142,  2075])

In [37]:
nonSparsePlaylistArtist[1:]

<45648x199 sparse matrix of type '<class 'numpy.int64'>'
	with 1040513 stored elements in Compressed Sparse Column format>

In [42]:
firstRow=array(zeros(17536))
for a in nonSparsePlaylistArtist[0].data:
    firstRow[where(artistIDs==a)[0][0]]+=1
firstRow=csr_matrix(firstRow)
for artists in nonSparsePlaylistArtist[1:]:
    newRow=array(zeros(17536))
    for a in artists.data:
        newRow[where(artistIDs==a)[0][0]]+=1
    firstRow=vstack((firstRow,newRow))
        

In [43]:
firstRow

<45649x17536 sparse matrix of type '<class 'numpy.float64'>'
	with 676931 stored elements in COOrdinate format>

In [48]:
sparsePlaylistArtist=csr_matrix(firstRow)
sparsePlaylistArtist

<45649x17536 sparse matrix of type '<class 'numpy.float64'>'
	with 676931 stored elements in Compressed Sparse Row format>

In [61]:
save_npz("fucking_ordered_playlist_artist.npz",sparsePlaylistArtist)

prova per vedere se funziona

In [78]:
load_npz("fucking_ordered_playlist_artist.npz")

<45649x17536 sparse matrix of type '<class 'numpy.float64'>'
	with 676931 stored elements in Compressed Sparse Row format>

In [77]:
load_npz("fucking_ordered_playlist_artist.npz")[14265].data

array([ 8.])

In [75]:
load_npz("fucking_ordered_playlist_artist.npz")[14265].nonzero()

(array([0], dtype=int32), array([13666], dtype=int32))

In [76]:
artistIDs[13666]

359758

In [71]:
load("target_playlist_mono_artist.npy")[0]

array([4902536,  359758], dtype=int32)

In [66]:
allP=load("fucking_ordered_playlist.npy")

In [69]:
where(allP==4902536)[0][0]

14265

In [90]:
sorted(nonSparsePlaylistArtist[0].data)

[20683, 22096, 53362, 54765, 281045, 281045, 319024, 319024, 449220]

In [84]:
load_npz("fucking_ordered_playlist_artist.npz")[0].data

array([ 1.,  1.,  1.,  1.,  2.,  2.,  1.])

In [88]:
load_npz("fucking_ordered_playlist_artist.npz")[0].nonzero()[1]

array([  646,   723,  2075,  2142, 10548, 11937, 16741], dtype=int32)

In [89]:
artistIDs[load_npz("fucking_ordered_playlist_artist.npz")[0].nonzero()[1]]

array([ 20683,  22096,  53362,  54765, 281045, 319024, 449220], dtype=int32)