In [1]:
from numpy import *
from scipy.sparse import *

In [3]:
trackAlbum=load("tracks_with_album.npy").astype(int32)
trackAlbum

array([[2972914,       7],
       [2750239,       8],
       [1550729,       9],
       ..., 
       [2584455,       0],
       [2299706,       0],
       [2739985,       0]], dtype=int32)

In [17]:
trackAlbum_Tr=trackAlbum[:,0]
trackAlbum_Al=trackAlbum[:,1]

In [100]:
tPlTr_full=load("playlists_with_tracks.npy")
tPlTr_full

array([[10024884,  2879006,  1532328, ...,        0,        0,        0],
       [10624787,  2090319,  2152295, ...,        0,        0,        0],
       [ 4891851,  2621486,  2895498, ...,        0,        0,        0],
       ..., 
       [11369546,   416692,  1587449, ...,        0,        0,        0],
       [ 7939535,  2788577,  3090083, ...,        0,        0,        0],
       [  297021,  2789282,  2154608, ...,        0,        0,        0]])

In [101]:
tPlTr_PlID=tPlTr_full[:,0]
tPlTr_PlID

array([10024884, 10624787,  4891851, ..., 11369546,  7939535,   297021])

In [102]:
tPlTr_Tr=tPlTr_full[:,1:]
tPlTr_Tr# when loaded it contains the tracks, it will be overwritten later with the albums

array([[2879006, 1532328, 3027673, ...,       0,       0,       0],
       [2090319, 2152295, 3230559, ...,       0,       0,       0],
       [2621486, 2895498, 1369381, ...,       0,       0,       0],
       ..., 
       [ 416692, 1587449, 1057389, ...,       0,       0,       0],
       [2788577, 3090083, 1609308, ...,       0,       0,       0],
       [2789282, 2154608,  973448, ...,       0,       0,       0]])

In [103]:
tPlTr_PlID.shape,tPlTr_Tr.shape

((10000,), (10000, 192))

In [104]:
for i,tracks in enumerate(tPlTr_Tr):
    thisAlbums=[]
    for t in tracks.data:
        if(t!=0):
            thisAlbum=trackAlbum_Al[where(trackAlbum_Tr==t)[0][0]]
            #if(thisAlbum!=0):
            thisAlbums+=[thisAlbum]
    thisAlbums+=[0]*(192-len(thisAlbums))
    arrThisAlbum=array(thisAlbums)
    tPlTr_Tr[i]=arrThisAlbum# questo sovrascrive la variabile precedente

In [105]:
tPlTr_Tr# ora contiene gli album

array([[155542,  21332, 180843, ...,      0,      0,      0],
       [194582,      0,  21983, ...,      0,      0,      0],
       [ 49381,      0, 137984, ...,      0,      0,      0],
       ..., 
       [136287,  10415, 199289, ...,      0,      0,      0],
       [148968, 116312,      0, ...,      0,      0,      0],
       [209144,  51695,      0, ...,      0,      0,      0]])

In [107]:
unique(tPlTr_Tr[0])

array([     0,  14964,  15936,  17890,  21332,  24878,  26276,  27090,
        27094,  35811,  55660,  58832,  60169,  61860,  71011,  78243,
        87168,  91881,  91883,  93903,  96591,  98872,  99104, 110290,
       112282, 118320, 118339, 130564, 130566, 130573, 130577, 131754,
       135317, 135406, 145367, 151944, 154538, 155542, 155543, 155544,
       156395, 163186, 164794, 164801, 174564, 176668, 180843, 205394,
       207297, 215799])

In [108]:
save("playlistsID_with_albumsID_with_zero.npy",tPlTr_full)

In [135]:
tPlAl=load("playlistsID_with_albumsID.npy")#la versione senza zeri non è affidabile, la versione con gli zeri nemmeno
tPlAl

array([[10024884,   155542,    21332, ...,        0,        0,        0],
       [10624787,   194582,    21983, ...,        0,        0,        0],
       [ 4891851,    49381,   137984, ...,        0,        0,        0],
       ..., 
       [11369546,   136287,    10415, ...,        0,        0,        0],
       [ 7939535,   148968,   116312, ...,        0,        0,        0],
       [  297021,   209144,    51695, ...,        0,        0,        0]])

In [136]:
tPlAl_Al=tPlAl[:,1:]
tPlAl_Al

array([[155542,  21332, 180843, ...,      0,      0,      0],
       [194582,  21983,  65092, ...,      0,      0,      0],
       [ 49381, 137984,  46756, ...,      0,      0,      0],
       ..., 
       [136287,  10415, 199289, ...,      0,      0,      0],
       [148968, 116312, 116289, ...,      0,      0,      0],
       [209144,  51695, 194176, ...,      0,      0,      0]])

In [143]:
monoAlbum=[]
for plID,albums in zip(tPlTr_PlID,tPlAl_Al):
    uniqueAlbums=trim_zeros(unique(albums))
    if(uniqueAlbums.size==1):
        thisPl=[]
        thisPl+=[plID]
        thisPl+=[uniqueAlbums[0]]
        monoAlbum.append(thisPl)

In [144]:
len(monoAlbum),monoAlbum

(124,
 [[6322279, 211564],
  [11511853, 47689],
  [6424137, 66178],
  [984152, 191956],
  [8966299, 45426],
  [4237429, 45302],
  [2277883, 136080],
  [6106692, 87952],
  [11198477, 206056],
  [112076, 146565],
  [5643598, 28436],
  [3927159, 26700],
  [8375176, 51993],
  [7979063, 25282],
  [1479496, 87952],
  [13957, 105710],
  [6982608, 32091],
  [10595529, 171485],
  [6404178, 44348],
  [562489, 131943],
  [3067099, 44348],
  [11049398, 115476],
  [5451874, 107153],
  [11475868, 207890],
  [5878211, 209812],
  [6296233, 74726],
  [10662505, 190522],
  [11184032, 164677],
  [4281172, 216598],
  [6906924, 111528],
  [7550576, 148691],
  [10477991, 84936],
  [11746847, 176796],
  [7385365, 2006],
  [8086834, 174811],
  [130817, 30687],
  [6066487, 195342],
  [11319088, 154473],
  [7589452, 174811],
  [8497050, 103225],
  [6147891, 111528],
  [6641136, 82554],
  [11724383, 140675],
  [8540431, 18869],
  [11756453, 108602],
  [5146018, 196282],
  [8456826, 194923],
  [5332194, 179409],


In [133]:
arrMonoAlbum=array(monoAlbum)
arrMonoAlbum

ValueError: setting an array element with a sequence.