In [1]:
from numpy import *
from scipy.sparse import *

In [2]:
allPlTracks=load_npz("all_playlists_with_tracks.npz")
allPlTracks.shape

(45649, 200)

In [3]:
allPlOnlyIDs=allPlTracks[:,0]
allPlOnlyIDs.data,allPlOnlyIDs.size

(array([    7569,     7614,     7641, ..., 11765405, 11766293, 11766362]),
 45649)

In [4]:
allPlOnlyTracks=allPlTracks[:,1:]
allPlOnlyTracks.shape

(45649, 199)

In [5]:
highestTrackID=max([max(l.data) for l in allPlOnlyTracks])

In [6]:
highestTrackID

5018274

In [7]:
allTracksIDs=genfromtxt("tracks_final.csv",skip_header=1,dtype=int32,usecols=0)

In [8]:
allTracksIDs=unique(allTracksIDs)
numTracks=100000
allTracksIDs

array([    252,     360,     394, ..., 5007354, 5014702, 5018274], dtype=int32)

In [12]:
allPlOnlyTracks[0].data

array([2634448, 2693660, 2227105, 2654612,  162463, 1195736, 2861386,
        795606,  421750])

In [15]:
firstRow=[0]*100000
for t in allPlOnlyTracks[0].data:
    firstRow[where(allTracksIDs==t)[0][0]]=1
firstMatRow=csr_matrix(firstRow)
vstack((firstMatRow,firstMatRow))

<2x100000 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [16]:
firstRow=[0]*100000
for t in allPlOnlyTracks[0].data:
    firstRow[where(allTracksIDs==t)[0][0]]=1
firstMatRow=csr_matrix(firstRow)
for tracks in allPlOnlyTracks[1:]:
    thisZeroOne=[0]*100000
    for t in tracks.data:
        thisZeroOne[where(allTracksIDs==t)[0][0]]=1
    firstMatRow=vstack((firstMatRow,csr_matrix(thisZeroOne)))

In [46]:
firstMatRow=firstMatRow.tocsc().astype(int32)

In [47]:
firstMatRow

<45649x100000 sparse matrix of type '<class 'numpy.int32'>'
	with 1040522 stored elements in Compressed Sparse Column format>