In [1]:
from numpy import *
from scipy.sparse import *

In [2]:
artistTracks=load_npz("artists_with_tracksID_ordered_by_occurrencies.npz")
artistTracks

<17536x221 sparse matrix of type '<class 'numpy.int64'>'
	with 100000 stored elements in Compressed Sparse Column format>

In [4]:
trackArtist=load("track_artist.npy")
trackArtist

array([[2972914,     144],
       [2750239,     246],
       [1550729,     144],
       ..., 
       [2584455,   27938],
       [2299706,  373892],
       [2739985,  567363]], dtype=int32)

In [6]:
artistIDs=unique(trackArtist[:,1])
artistIDs,artistIDs.size

(array([    78,    109,    144, ..., 567363, 568165, 570588], dtype=int32),
 17536)

In [8]:
trackTag=load("tracks_with_tags.npy")
trackTag

array([[2972914,   54087,    1757,    1718,  116712,  189631],
       [2750239,  189631,    3424,  177424,   46208,  205245],
       [1550729,   54087,  109806,   46869,  183258,   54337],
       ..., 
       [2584455,       0,       0,       0,       0,       0],
       [2299706,       0,       0,       0,       0,       0],
       [2739985,       0,       0,       0,       0,       0]], dtype=int32)

In [13]:
onlyTrackIDs=trackTag[:,0]
onlyTrackIDs

array([2972914, 2750239, 1550729, ..., 2584455, 2299706, 2739985], dtype=int32)

In [14]:
onlyTrackTags=trackTag[:,1:]
onlyTrackTags

array([[ 54087,   1757,   1718, 116712, 189631],
       [189631,   3424, 177424,  46208, 205245],
       [ 54087, 109806,  46869, 183258,  54337],
       ..., 
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0]], dtype=int32)

In [29]:
where(onlyTrackIDs==2584455)[0][0]

99997

In [30]:
artistsTag=[]
for tracks in artistTracks:
    thisTags=[]
    for t in tracks.data:
        i=where(onlyTrackIDs==t)[0][0]
        thisTags+=list(onlyTrackTags[i])
    artistsTag.append(thisTags)

In [32]:
max([len(a) for a in artistsTag])

1105

In [33]:
221*5

1105

In [38]:
maxTag=max([max(t) for t in onlyTrackTags])
maxSize=maxTag+1
maxSize

276615

In [44]:
A=lil_matrix((17536,maxSize))
for i,tags in enumerate(artistsTag):
    A[i]=bincount(tags, minlength=maxSize)

In [53]:
A=csc_matrix(A)
A

<17536x276615 sparse matrix of type '<class 'numpy.float64'>'
	with 179276 stored elements in Compressed Sparse Column format>

In [61]:
for i in range(1,276615):
    if(A.getcol(i).size!=0):
        print(i)
        break

22


In [65]:
firstCol=A.getcol(22)
for i in range(23,276615):
    thisCol=A.getcol(i)
    if(thisCol.size!=0):
        firstCol=hstack((firstCol,thisCol))

In [71]:
firstCol=firstCol.astype(int16)

In [72]:
save_npz("artist_with_tag_bincount_reduced.npz",firstCol)

In [73]:
testResult=load_npz("artist_with_tag_bincount_reduced.npz")
testResult

<17536x31900 sparse matrix of type '<class 'numpy.int16'>'
	with 176915 stored elements in Compressed Sparse Column format>