In [95]:
from numpy import *
from scipy.sparse import *

In [96]:
allPAr=load_npz("all_playlists_with_artist.npz")
allPTa=load_npz("all_playlists_with_tags.npz")
allPTr=load_npz("all_playlists_with_tracks.npz")

In [99]:
allPlIDs=allPTr[:,0]
allPlIDs=ravel(allPlIDs.todense())
allPlIDs,pIDs.size

(array([    7569,     7614,     7641, ..., 11765405, 11766293, 11766362]),
 45649)

In [27]:
# save("allPlaylistIDsIndex.npy",pIDs)

In [100]:
tPlIDs=genfromtxt("target_playlists.csv",skip_header=1,dtype=int32)
tPlIDs

array([10024884, 10624787,  4891851, ..., 11369546,  7939535,   297021], dtype=int32)

In [101]:
ntPlIDs=load("non_target_pl_indexes.npy")
ntPlIDs,nonTargetIDs.size

(array([    7569,     7641,     7912, ..., 11764165, 11764751, 11766293]),
 35649)

In [110]:
tPlIDs=genfromtxt("target_playlists.csv",skip_header=1,dtype=int32)
tPlIDs,tPlIDs.size

(array([10024884, 10624787,  4891851, ..., 11369546,  7939535,   297021], dtype=int32),
 10000)

In [114]:
tPlAr=load_npz("targetPlaylistArtistReduced.npz")

In [104]:
k1=0
k2=0
k3=0
for p in tPAr:
    if(p.size==1):
        k1+=1
    elif(p.size==2):
        k2+=1
    elif(p.size==3):
        k3+=1
print(k1,k2,k3,k1+k2+k3)

529 116 128 773


In [108]:
artistIDs=load("uniqueArtists_NeededToIndexThe_ArtistReducedMatrices.npy")
artistIDs,artistIDs.size

(array([    78,    109,    144, ..., 567363, 568165, 570588], dtype=int32),
 17536)

In [121]:
tPlAr[0].nonzero()[1][0]

1135

In [120]:
tPlIDs[0]

10024884

In [124]:
artistIDs[0]

78

In [143]:
#monoartist
plMonoArt=[]
for artBinc,pID in zip(tPlAr,tPlIDs):
    if(artBinc.size==1):
        thisPl=[]
        thisPl+=[pID]
        thisArt=artistIDs[artBinc.nonzero()[1][0]]
        thisPl+=[thisArt]
        plMonoArt.append(thisPl)

In [144]:
arrPlMonoArt=array(plMonoArt)
arrPlMonoArt,arrPlMonoArt.shape

(array([[ 4902536,   359758],
        [ 8910289,   379748],
        [ 6611489,   153172],
        ..., 
        [ 5082388,   228054],
        [ 8344678,   325151],
        [11542825,   148256]], dtype=int32), (529, 2))

In [145]:
save("target_playlist_mono_artist.npy",arrPlMonoArt)

In [152]:
#biartist
plBiArt=[]
for artBinc,pID in zip(tPlAr,tPlIDs):
    if(artBinc.size==2):
        thisPl=[]
        thisPl+=[pID]
        for a in artBinc.nonzero()[1]:
            thisArt=artistIDs[a]
            thisPl+=[thisArt]
        plBiArt.append(thisPl)

In [158]:
arrPlBiArt=array(plBiArt)
arrPlBiArt.shape

(116, 3)

In [159]:
save("target_playlist_bi_artist.npy",arrPlBiArt)

In [169]:
load("target_playlist_mono_artist.npy")[:,1].nonzero()[0].size

529