In [1]:
from numpy import *
from scipy.sparse import *

In [2]:
trackArtist=genfromtxt("tracks_final.csv",usecols=[0,1],skip_header=1,dtype=[("trackID",int32),("artistID",int32)])
trackArtist

array([(2972914,    144), (2750239,    246), (1550729,    144), ...,
       (2584455,  27938), (2299706, 373892), (2739985, 567363)],
      dtype=[('trackID', '<i4'), ('artistID', '<i4')])

In [3]:
trackArtist.sort(order="trackID")
trackArtist

array([(    252, 276973), (    360, 169649), (    394, 317842), ...,
       (5007354, 342450), (5014702, 371784), (5018274, 316207)],
      dtype=[('trackID', '<i4'), ('artistID', '<i4')])

In [4]:
trackArtist=array(list(map(lambda x: [x[0],x[1]],trackArtist)))

In [66]:
trackArtist,trackArtist.shape

(array([[    252,  276973],
        [    360,  169649],
        [    394,  317842],
        ..., 
        [5007354,  342450],
        [5014702,  371784],
        [5018274,  316207]], dtype=int32), (100000, 2))

In [15]:
orderedArtists=unique(trackArtist[:,1])
orderedArtists.size,orderedArtists


(17536,
 array([    78,    109,    144, ..., 567363, 568165, 570588], dtype=int32))

In [14]:
orderedTracks=trackArtist[:,0]
orderedTracks.size,orderedTracks

(100000,
 array([    252,     360,     394, ..., 5007354, 5014702, 5018274], dtype=int32))

In [77]:
save("fucking_ordered_tracks",orderedTracks)
save("fucking_ordered_artists",orderedArtists)
save("fucking_ordered_albums",orderedAlbums)

In [12]:
firstRow=[0]*17536
firstRow[where(orderedArtists==trackArtist[0][1])[0][0]]=1
firstRow=csr_matrix(firstRow)
for t,a in trackArtist[1:]:
    thisRow=[0]*17536
    thisRow[where(orderedArtists==a)[0][0]]=1
    firstRow=vstack((firstRow,csr_matrix(thisRow)))

In [13]:
firstRow

<100000x17536 sparse matrix of type '<class 'numpy.int64'>'
	with 100000 stored elements in Compressed Sparse Row format>

In [17]:
save_npz("fucking_ordered_track_artist.npz",firstRow)#tutto ordinato per ID

In [67]:
trackAlbum=load("track_artist_album.npy")
trackAlbum=array(list(map(lambda x:[x[0],x[2]],trackAlbum)))
trackAlbum[0:15]

array([[2972914,       7],
       [2750239,       8],
       [1550729,       9],
       [2169950,       9],
       [1903709,       0],
       [2256817,       9],
       [2561768,      26],
       [ 474864,      22],
       [1378455,      22],
       [1523190,      22],
       [1373492,      22],
       [3387498,      31],
       [ 699524,      26],
       [2438345,      22],
       [  47604,      38]])

In [68]:
trackAlbum=array(list(map(lambda x: [x[0],x[1]],sorted(trackAlbum,key=lambda x:x[0]))))
trackAlbum,trackAlbum.shape

(array([[    252,  127477],
        [    360,   77662],
        [    394,  146024],
        ..., 
        [5007354,  157661],
        [5014702,  175831],
        [5018274,       0]]), (100000, 2))

In [71]:
orderedAlbums=(unique(trackAlbum[:,1]))[1:]
orderedAlbums,orderedAlbums.size

(array([     6,      7,      8, ..., 217314, 217324, 217325]), 27604)

In [73]:
firstRow=[0]*27604
firstRow[where(orderedAlbums==trackAlbum[0][1])[0][0]]=1
firstRow=csr_matrix(firstRow)
for t,a in trackAlbum[1:]:
    thisRow=[0]*27604
    if(a!=0):
        thisRow[where(orderedAlbums==a)[0][0]]=1
    firstRow=vstack((firstRow,csr_matrix(thisRow)))

In [74]:
firstRow

<100000x27604 sparse matrix of type '<class 'numpy.int64'>'
	with 73244 stored elements in Compressed Sparse Row format>

In [76]:
save_npz("fucking_ordered_track_album.npz",firstRow)