In [18]:
from scipy.sparse import *
from numpy import *

In [27]:
plWithTracks=load_npz("all_playlists_with_tracks.npz")
plIDs=plWithTracks[:,0].data
plTracks=plWithTracks[:,1:]
plIDs,plTracks

(array([    7569,     7614,     7641, ..., 11765405, 11766293, 11766362]),
 <45649x199 sparse matrix of type '<class 'numpy.int64'>'
 	with 1040522 stored elements in Compressed Sparse Column format>)

In [34]:
#fatto e ora non serve più
with open("three_columns_playlist_tracks","w") as f:
    for plID,thisPlTracks in zip(plIDs,plTracks):
        for track in thisPlTracks.data:
            f.write(str(plID)+" "+str(track)+" 1"+ "\n")
        
        

In [36]:
URM_threeCol=genfromtxt("three_columns_playlist_tracks",dtype=int32)
URM_threeCol

array([[    7569,  2634448,        1],
       [    7569,  2693660,        1],
       [    7569,  2227105,        1],
       ..., 
       [11766362,   732266,        1],
       [11766362,   512935,        1],
       [11766362,  2733715,        1]], dtype=int32)

In [37]:
playlistList=list(URM_threeCol[:,0])
trackList=list(URM_threeCol[:,1])
ratingList=list(URM_threeCol[:,2])

In [39]:
playlistList[0:10]

[7569, 7569, 7569, 7569, 7569, 7569, 7569, 7569, 7569, 7614]

In [42]:
trackList[0:8]

[2634448, 2693660, 2227105, 2654612, 162463, 1195736, 2861386, 795606]

In [43]:
ratingList[0:20]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [119]:
#ne manca unaaaaaa merdaaaaaa 3626362
all100k=load("ordered_tracks.npy").astype(int32)
all100k.sort()
where(all100k==3626362)[0][0]#92865
setdiff1d(all100k,unique(trackList))

array([3626362], dtype=int32)

In [121]:
filter1.size

11766363

In [114]:
URM_all=csc_matrix((ratingList,(playlistList,trackList)))
filter1=URM_all.getnnz(1)>0
filter2=URM_all.getnnz(0)>0
URM_all=URM_all[filter1][:,filter2]
URM_all

<45649x99999 sparse matrix of type '<class 'numpy.int32'>'
	with 1040522 stored elements in Compressed Sparse Column format>

In [98]:
URM_all.getcol(0)

<45649x1 sparse matrix of type '<class 'numpy.int32'>'
	with 13 stored elements in Compressed Sparse Column format>

In [97]:
csc_matrix(zeros(45649)).T

<45649x1 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [112]:
train_test_split = 0.80

numInteractions = URM_all.nnz


train_mask = random.choice([True,False], numInteractions, p=[train_test_split, 1-train_test_split])
train_mask

array([False,  True,  True, ...,  True, False,  True], dtype=bool)

In [115]:
playlistList=array(playlistList)
trackList=array(trackList)
ratingList=array(ratingList)

URM_train=(coo_matrix((ratingList[train_mask],(playlistList[train_mask],trackList[train_mask]))))
URM_train=URM_train.tocsr()[filter1][:,filter2]
URM_train

<45649x99999 sparse matrix of type '<class 'numpy.int32'>'
	with 832635 stored elements in Compressed Sparse Row format>

In [117]:
test_mask=logical_not(train_mask)
URM_test=(coo_matrix((ratingList[test_mask],(playlistList[test_mask],trackList[test_mask]))))
URM_test=URM_test.tocsr()[filter1][:,filter2]
URM_test

<45649x99999 sparse matrix of type '<class 'numpy.int32'>'
	with 207887 stored elements in Compressed Sparse Row format>