In [2]:
from numpy import *
from scipy import *
from scipy.sparse import *
from scipy.spatial.distance import *
from sklearn.preprocessing import *

In [2]:
tracks_with_tags=load("tracks_with_tags.npy")
tracks_with_tags

array([[2972914,   54087,    1757,    1718,  116712,  189631],
       [2750239,  189631,    3424,  177424,   46208,  205245],
       [1550729,   54087,  109806,   46869,  183258,   54337],
       ..., 
       [2584455,       0,       0,       0,       0,       0],
       [2299706,       0,       0,       0,       0,       0],
       [2739985,       0,       0,       0,       0,       0]], dtype=int32)

In [10]:
allTrackTags=tracks_with_tags[:,1:]
allTrackTags

array([[ 54087,   1757,   1718, 116712, 189631],
       [189631,   3424, 177424,  46208, 205245],
       [ 54087, 109806,  46869, 183258,  54337],
       ..., 
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0]], dtype=int32)

In [9]:
allTrackIDs=tracks_with_tags[:,0]
allTrackIDs

array([2972914, 2750239, 1550729, ..., 2584455, 2299706, 2739985], dtype=int32)

In [7]:
targetTrackIDs=genfromtxt("target_tracks.csv",skip_header=1,dtype=int32)
targetTrackIDs.size

32195

In [12]:
reducedP=load_npz("playlist_reduced.npz")

In [5]:
allTracksOrdered=load("ordered_tracks.npy")
allTracksOrdered.size

100000

In [25]:
allTracksOrdered[0]

1563309.0

In [4]:
allTracksTags=load_npz("tracks_ordered_tags_reduced.npz")
allTracksTags.shape

(100000, 31900)

In [23]:
allTracksTags.getrow(0)

<1x31900 sparse matrix of type '<class 'numpy.int8'>'
	with 5 stored elements in Compressed Sparse Row format>

In [8]:
for i in range(100000):
    if (not isin(allTracksOrdered[i],targetTrackIDs)):
        print(i)
        break

426


In [43]:
startingRow=allTracksTags.getrow(0)
for i in range(1,100000):
    if (isin(allTracksOrdered[i],targetTrackIDs)):
        startingRow=vstack((startingRow,allTracksTags.getrow(i)))

In [45]:
startingRow

<32195x31900 sparse matrix of type '<class 'numpy.int8'>'
	with 156621 stored elements in Compressed Sparse Row format>

In [46]:
type(startingRow)

scipy.sparse.csr.csr_matrix

In [47]:
save_npz("reducedTargetT.npz",startingRow)

In [3]:
orderedIndexes=load("indexsortedDESCENDENT.npy")
orderedIndexes

array([43529, 94738, 57501, ..., 17820, 79618, 43000])

In [15]:
orderedTargetIndexes=array(orderedIndexes[0])
for i in range(1,100000):
    if (isin(allTracksOrdered[i],targetTrackIDs)):
        orderedTargetIndexes=append(orderedTargetIndexes,orderedIndexes[i])

In [14]:
orderedTargetIndexes=array(orderedIndexes[0])
orderedTargetIndexes=append(orderedTargetIndexes,orderedIndexes[1])
orderedTargetIndexes

array([43529, 94738])

In [21]:
orderedTargetIndexes.size

32195

In [20]:
orderedIndexes.size

100000

In [17]:
save("orderedTargetIndexes.npy",orderedTargetIndexes)