In [1]:
from numpy import *
from scipy.sparse import *
from sklearn.preprocessing import *

In [2]:
M=load_npz("reducedTargetT.npz")

In [8]:
M.shape

(32195, 31900)

In [9]:
M[0].data

array([1, 1, 1, 1, 1], dtype=int8)

In [4]:
trackSim=M*M.T

In [7]:
trackSim

<32195x32195 sparse matrix of type '<class 'numpy.int8'>'
	with 214523619 stored elements in Compressed Sparse Row format>

In [9]:
trackSim.setdiag(0)

/home/oppy/.local/lib/python3.5/site-packages/scipy/sparse/compressed.py:774: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


In [3]:
P=load_npz("playlist_reduced.npz")
P=normalize(P)

In [6]:
P[0].data

array([ 0.01087342,  0.01087342,  0.02174684,  0.01087342,  0.01087342,
        0.01087342,  0.23921524,  0.01087342,  0.2174684 ,  0.0543671 ,
        0.01087342,  0.02174684,  0.01087342,  0.2174684 ,  0.0543671 ,
        0.56541783,  0.01087342,  0.01087342,  0.01087342,  0.01087342,
        0.01087342,  0.01087342,  0.01087342,  0.01087342,  0.01087342,
        0.06524052,  0.01087342,  0.01087342,  0.01087342,  0.01087342,
        0.57629125,  0.06524052,  0.01087342,  0.13048104,  0.01087342,
        0.01087342,  0.01087342,  0.01087342,  0.02174684,  0.01087342,
        0.01087342,  0.02174684,  0.01087342,  0.1087342 ,  0.01087342,
        0.01087342,  0.01087342,  0.01087342,  0.01087342,  0.3805697 ,
        0.02174684,  0.01087342,  0.01087342,  0.01087342,  0.01087342,
        0.01087342,  0.01087342,  0.01087342,  0.01087342,  0.01087342,
        0.01087342,  0.02174684,  0.01087342,  0.01087342])

In [4]:
PlTrackSim=P*M.T
PlTrackSim

<10000x32195 sparse matrix of type '<class 'numpy.float64'>'
	with 197566599 stored elements in Compressed Sparse Row format>

In [9]:
maxTargetIndex=PlTrackSim.argmax(1)

In [13]:
maxTargetIndex=maxTargetIndex.flatten()
maxTargetIndex

matrix([[   21,  2188, 13123, ..., 12357,  1626,   371]])