In [1]:
from numpy import *
from scipy.sparse import *
from sklearn.preprocessing import *

In [5]:
M=load_npz("reducedTargetT.npz")

In [6]:
M.shape

(32195, 31900)

In [7]:
M[0].data

array([1, 1, 1, 1, 1], dtype=int8)

In [5]:
trackSim=M*M.T

In [6]:
trackSim

<32195x32195 sparse matrix of type '<class 'numpy.int8'>'
	with 214523619 stored elements in Compressed Sparse Row format>

In [2]:
P=load_npz("playlist_reduced.npz")
P=normalize(P)

In [3]:
P[0].data

array([ 0.01886792,  0.01886792,  0.03773585,  0.01886792,  0.01886792,
        0.01886792,  0.41509434,  0.01886792,  0.37735849,  0.09433962,
        0.01886792,  0.03773585,  0.01886792,  0.37735849,  0.09433962,
        0.98113208,  0.01886792,  0.01886792,  0.01886792,  0.01886792,
        0.01886792,  0.01886792,  0.01886792,  0.01886792,  0.01886792,
        0.11320755,  0.01886792,  0.01886792,  0.01886792,  0.01886792,
        1.        ,  0.11320755,  0.01886792,  0.22641509,  0.01886792,
        0.01886792,  0.01886792,  0.01886792,  0.03773585,  0.01886792,
        0.01886792,  0.03773585,  0.01886792,  0.18867925,  0.01886792,
        0.01886792,  0.01886792,  0.01886792,  0.01886792,  0.66037736,
        0.03773585,  0.01886792,  0.01886792,  0.01886792,  0.01886792,
        0.01886792,  0.01886792,  0.01886792,  0.01886792,  0.01886792,
        0.01886792,  0.03773585,  0.01886792,  0.01886792])

In [8]:
PlTrackSim=P*M.T
PlTrackSim

<10000x32195 sparse matrix of type '<class 'numpy.float64'>'
	with 197566599 stored elements in Compressed Sparse Row format>

In [9]:
save_npz("target_pl_x_target_tracks_similarity.npz", PlTrackSim)

In [10]:
target_playlists=genfromtxt("target_playlists.csv",skip_header=1)
playlists_with_tracks=load("playlists_with_tracks.npy")
playlists_with_tracks

array([[10024884,  2879006,  1532328, ...,        0,        0,        0],
       [10624787,  2090319,  2152295, ...,        0,        0,        0],
       [ 4891851,  2621486,  2895498, ...,        0,        0,        0],
       ..., 
       [11369546,   416692,  1587449, ...,        0,        0,        0],
       [ 7939535,  2788577,  3090083, ...,        0,        0,        0],
       [  297021,  2789282,  2154608, ...,        0,        0,        0]], dtype=int64)

In [14]:
target_tracks_ordered = load("target_tracks_ordered.npy")

In [46]:
fname = "msimilarity.csv"
open(fname,"w").close()
print("playlist_id,track_ids",file=open(fname,"a"))
for pl, simil in zip(playlists_with_tracks, PlTrackSim):
    s = str(int(pl[0]))
    s += ","
    r = getsimil(pl, ravel(simil.todense()))
    for el in r:
        s+=str(el)
        s+=" "
    print(s,file=open(fname,"a"))

In [45]:
def getsimil(pls, similrow):
    maxi = flip(argsort(similrow), axis=0)
    r = []
    for m in maxi:
        if(not isin(target_tracks_ordered[m], pls[1:])):
           r.append(target_tracks_ordered[m])
           if(len(r)==5):
               return r