Imports:

In [7]:
from numpy import *
from scipy import *

Load Tracks with playcounts:

In [46]:
tracklist = genfromtxt('tracks_final.csv', skip_header=1, usecols=(0, 3), missing_values="nan", filling_values="0")

playlists

In [47]:
playlist_songs = genfromtxt('train_final.csv', skip_header=1, dtype="int64")

In [48]:
trackmask_count = bincount(playlist_songs[:,1])

In [49]:
z = column_stack((tracklist[:,0], tracklist[:,1], zeros(tracklist[:,0].size)))
z = z.astype("int64")


In [55]:
for x in range(0, z[:,1].size):
    z[x,2] = trackmask_count[z[x,0]]  

z

array([[2972914,      49,       8],
       [2750239,       1,      12],
       [1550729,     554,      37],
       ..., 
       [2584455,       0,       4],
       [2299706,       0,       4],
       [2739985,       0,       4]], dtype=int64)

In [56]:
k = column_stack((z[:,0], z[:,1], z[:,2], zeros(z[:,1].size)))

k[:,3]=k[:,1]+k[:,2]

array([[  2.97291400e+06,   4.90000000e+01,   8.00000000e+00,
          5.70000000e+01],
       [  2.75023900e+06,   1.00000000e+00,   1.20000000e+01,
          1.30000000e+01],
       [  1.55072900e+06,   5.54000000e+02,   3.70000000e+01,
          5.91000000e+02],
       ..., 
       [  2.58445500e+06,   0.00000000e+00,   4.00000000e+00,
          4.00000000e+00],
       [  2.29970600e+06,   0.00000000e+00,   4.00000000e+00,
          4.00000000e+00],
       [  2.73998500e+06,   0.00000000e+00,   4.00000000e+00,
          4.00000000e+00]])

In [62]:
indexsorted = argsort(k[:,2])
indexsorted

array([43000, 79618, 17820, ..., 57501, 94738, 43529], dtype=int64)

In [66]:
indexsortedASCENDENT = flip(indexsorted, 0)
indexsortedASCENDENT

array([43529, 94738, 57501, ..., 17820, 79618, 43000], dtype=int64)

FINE