Imports:

In [4]:
from numpy import *
from scipy import *

Load Tracks with playcounts:

In [5]:
tracklist = genfromtxt('tracks_final.csv', skip_header=1, usecols=(0, 3), missing_values="nan", filling_values="0")

playlists

In [6]:
playlist_songs = genfromtxt('train_final.csv', skip_header=1, dtype="int64")

In [7]:
trackmask_count = bincount(playlist_songs[:,1])

In [8]:
z = column_stack((tracklist[:,0], tracklist[:,1], zeros(tracklist[:,0].size)))
z = z.astype("int64")


In [9]:
for x in range(0, z[:,1].size):
    z[x,2] = trackmask_count[z[x,0]]  

z

array([[2972914,      49,       8],
       [2750239,       1,      12],
       [1550729,     554,      37],
       ..., 
       [2584455,       0,       4],
       [2299706,       0,       4],
       [2739985,       0,       4]])

In [72]:
k = column_stack((z[:,0], z[:,1], z[:,2], zeros(z[:,1].size)))

k[:,3]=k[:,1]+k[:,2]

k

array([[  2.97291400e+06,   4.90000000e+01,   8.00000000e+00,
          5.70000000e+01],
       [  2.75023900e+06,   1.00000000e+00,   1.20000000e+01,
          1.30000000e+01],
       [  1.55072900e+06,   5.54000000e+02,   3.70000000e+01,
          5.91000000e+02],
       ..., 
       [  2.58445500e+06,   0.00000000e+00,   4.00000000e+00,
          4.00000000e+00],
       [  2.29970600e+06,   0.00000000e+00,   4.00000000e+00,
          4.00000000e+00],
       [  2.73998500e+06,   0.00000000e+00,   4.00000000e+00,
          4.00000000e+00]])

In [116]:
indexsorted = argsort(k[:,2])
indexsorted

array([43000, 79618, 17820, ..., 57501, 94738, 43529])

In [117]:
indexsortedASCENDENT = flip(indexsorted, 0)
indexsortedASCENDENT

array([43529, 94738, 57501, ..., 17820, 79618, 43000])

FINE

verify results

In [118]:

for x in range(5):
    print(k[indexsortedASCENDENT[x]][2])

476.0
432.0
425.0
403.0
391.0


In [119]:
topNids=[]
for x in range(5):
    topNids.append(int(k[indexsortedASCENDENT[x]][0]))
topNids

[1563309, 1363985, 3705881, 1595978, 3166665]

In [120]:
target_playlists=genfromtxt("target_playlists.csv",skip_header=1)
target_playlists

array([ 10024884.,  10624787.,   4891851., ...,  11369546.,   7939535.,
          297021.])

In [122]:
print("playlist_id,track_ids",file=open("secondTopnSubmission.csv","a"))
topstr=""
for x in topNids:
    topstr+=str(x)
    topstr+=" "
for x in target_playlists:
    mystr=""
    mystr+=str(int(x))
    mystr+=","
    mystr+=topstr
    print(mystr,file=open("secondTopnSubmission.csv","a"))

punteggio di 0.00098 a questo punto