In [1]:
from numpy import *
from scipy.sparse import *

In [6]:
tracksWithTags=load("tracks_with_tags.npy")
tracksWithTags

array([[2972914,   54087,    1757,    1718,  116712,  189631],
       [2750239,  189631,    3424,  177424,   46208,  205245],
       [1550729,   54087,  109806,   46869,  183258,   54337],
       ..., 
       [2584455,       0,       0,       0,       0,       0],
       [2299706,       0,       0,       0,       0,       0],
       [2739985,       0,       0,       0,       0,       0]], dtype=int32)

In [7]:
tracksIDs=tracksWithTags[:,0]
tracksIDs

array([2972914, 2750239, 1550729, ..., 2584455, 2299706, 2739985], dtype=int32)

In [11]:
tracksTags=tracksWithTags[:,1:]
tracksTags

array([[ 54087,   1757,   1718, 116712, 189631],
       [189631,   3424, 177424,  46208, 205245],
       [ 54087, 109806,  46869, 183258,  54337],
       ..., 
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0],
       [     0,      0,      0,      0,      0]], dtype=int32)

In [12]:
allTags=[]
for tags in tracksTags:
    for t in tags:
        if(not t in allTags):
            allTags.append(t)

In [23]:
#allTags.remove(0)
len(allTags)

31900

In [25]:
arrayAllTags=array(allTags)
arrayAllTags,arrayAllTags.size

(array([ 54087,   1757,   1718, ...,  87957, 275594, 276430], dtype=int32),
 31900)

In [30]:
arrayAllTags=unique(arrayAllTags)
arrayAllTags,arrayAllTags.size

(array([    22,     26,     27, ..., 276604, 276605, 276614], dtype=int32),
 31900)

In [42]:
save("uniqueTags.npy",arrayAllTags)

In [33]:
where(arrayAllTags==27)[0][0]

2

In [36]:
tagsTotalFreq=[0]*31900
for tags in tracksTags:
    for t in tags:
        if t!=0:
            tagsTotalFreq[where(arrayAllTags==t)[0][0]]+=1

In [53]:
arrayTagsTotalFreq=array(tagsTotalFreq)
arrayTagsTotalFreq

array([5, 1, 1, ..., 2, 9, 1])

In [43]:
save("tagsTotalFrequency.npy",arrayTagsTotalFreq)

In [54]:
IDF=log(100000/arrayTagsTotalFreq)

In [55]:
IDF

array([  9.90348755,  11.51292546,  11.51292546, ...,  10.81977828,
         9.31570089,  11.51292546])

In [80]:
targetPlWithTagsBinc=load_npz("playlist_reduced.npz")
targetPlWithTagsBinc

<10000x31900 sparse matrix of type '<class 'numpy.float64'>'
	with 517048 stored elements in Compressed Sparse Column format>

In [81]:
allTracksWithTagsBinc=load_npz("tracks_ordered_tags_reduced.npz")
allTracksWithTagsBinc

<100000x31900 sparse matrix of type '<class 'numpy.int8'>'
	with 483482 stored elements in Compressed Sparse Column format>

In [94]:
firstCol=targetPlWithTagsBinc.getcol(0)
firstCol=firstCol*IDF[0]
firstCol
for i in range(1,31900):
    thisCol=targetPlWithTagsBinc.getcol(i)
    thisCol=thisCol*IDF[i]
    firstCol=hstack((firstCol,thisCol))

In [96]:
save_npz("target_playlist_tags_TF_IDF.npz",firstCol)

In [101]:
firstTrack=allTracksWithTagsBinc.getcol(0)
firstTrack=firstTrack*IDF[0]
firstTrack
for i in range(1,31900):
    newCol=allTracksWithTagsBinc.getcol(i)
    newCol=newCol*IDF[i]
    firstTrack=hstack((firstTrack,newCol))

In [103]:
save_npz("all_tracks_tags_TF_IDF.npz",firstTrack)

In [106]:
targetTracksWithTags=load_npz("reducedTargetT.npz")
targetTracksWithTags

<32195x31900 sparse matrix of type '<class 'numpy.int8'>'
	with 156621 stored elements in Compressed Sparse Row format>

In [108]:
firstTarget=targetTracksWithTags.getcol(0)
firstTarget=firstTarget*IDF[0]
firstTarget
for i in range(1,31900):
    newTarget=targetTracksWithTags.getcol(i)
    newTarget=newTarget*IDF[i]
    firstTarget=hstack((firstTarget,newTarget))

In [109]:
firstTarget

<32195x31900 sparse matrix of type '<class 'numpy.float64'>'
	with 156621 stored elements in COOrdinate format>

In [110]:
save_npz("target_tracks_tags_TF_IDF",firstTarget)