In [1]:
from numpy import *
from scipy import *

In [2]:
tracks_with_tags=load("tracks_with_tags.npy")
tracks_with_tags


array([[2972914,   54087,    1757,    1718,  116712,  189631],
       [2750239,  189631,    3424,  177424,   46208,  205245],
       [1550729,   54087,  109806,   46869,  183258,   54337],
       ..., 
       [2584455,       0,       0,       0,       0,       0],
       [2299706,       0,       0,       0,       0,       0],
       [2739985,       0,       0,       0,       0,       0]], dtype=int32)

In [10]:
tag_indexed_byidtrack = zeros((amax(tracks_with_tags[:,0])+1, 5))

transfer = lambda x, y: where(tracks_with_tags[:,0]==x)
    
for x in tracks_with_tags[:,0]:
    i = where(tracks_with_tags[:,0]==x)
    tag_indexed_byidtrack[x] = tracks_with_tags[i,1:]




In [12]:
tag_indexed_byidtrack.shape

(5018275, 5)

In [16]:
tag_indexed_byidtrack[1550729]

array([  54087.,  109806.,   46869.,  183258.,   54337.])

Ho creato un array che contiene tutti i tag delle canzoni con index l'id: 
tag_indexed_byidtrack[id] = [tags]

sveltirà di molto i calcoli successivi

In [4]:
playlists_with_tracks=load("playlists_with_tracks.npy")
playlists_with_tracks

array([[10024884,  2879006,  1532328, ...,        0,        0,        0],
       [10624787,  2090319,  2152295, ...,        0,        0,        0],
       [ 4891851,  2621486,  2895498, ...,        0,        0,        0],
       ..., 
       [11369546,   416692,  1587449, ...,        0,        0,        0],
       [ 7939535,  2788577,  3090083, ...,        0,        0,        0],
       [  297021,  2789282,  2154608, ...,        0,        0,        0]])

In [18]:
tracklist_by_playlist = delete(playlists_with_tracks, 0, 1)
tracklist_by_playlist

array([[2879006, 1532328, 3027673, ...,       0,       0,       0],
       [2090319, 2152295, 3230559, ...,       0,       0,       0],
       [2621486, 2895498, 1369381, ...,       0,       0,       0],
       ..., 
       [ 416692, 1587449, 1057389, ...,       0,       0,       0],
       [2788577, 3090083, 1609308, ...,       0,       0,       0],
       [2789282, 2154608,  973448, ...,       0,       0,       0]])

In [116]:
maxNumTracks=tracklist_by_playlist.shape[1]
maxNumTracks

192

In [154]:
highestTag=276614 # trovato ciclando sui tag
maxSize=highestTag+1

In [171]:
for tracks in tracklist_by_playlist:
    tracks=trim_zeros(tracks)
    alltags=[]
    for t in tracks:
        tags = tag_indexed_byidtrack[t]
        alltags+=list(tags)
    tagsArray=(array(alltags)).astype(int)
    tagsCount=bincount(tagsArray)#posizione = tagID, contenuto = conteggio di quel tag
    tagsCount[0]=0#altrimenti venivano contati anche gli zeri
    tagsCount=resize(tagsCount,(maxSize,))
    #TODO qui ad ogni iterazione andrebbe aggiunto il vettore tagsCount a una qualche matrice

# il ciclo qui sopra crea l'array dei tag per ogni playlist, manca solo che venga aggiunto a una qualche matrice

In [194]:
tagsCount.nonzero() # controllo ultima iterazione

(array([    51,   1477,   1625,   4425,   6120,   6745,  11056,  11242,
         13914,  21095,  21937,  24673,  24925,  27773,  31015,  33360,
         35060,  35233,  38403,  40088,  40686,  43212,  48958,  49166,
         50247,  50441,  52110,  54087,  60829,  61837,  62150,  70618,
         80483,  81211,  81223,  89467,  99955, 101507, 102673, 107401,
        112056, 115355, 121612, 122769, 124381, 126182, 127038, 128425,
        134636, 135090, 136980, 144192, 145120, 148788, 150480, 151588,
        153432, 166531, 167551, 168507, 178918, 181499, 186445, 186591,
        187116, 188569, 189631, 190112, 199405, 199968, 204111, 204710,
        205193, 205245, 207056, 209598, 211198, 213988, 215342, 215851,
        216001, 218701, 226723, 227682, 228654, 235879, 238367, 239887,
        260159, 266268, 270345, 270397, 271823, 271971, 274771, 276466]),)