In [16]:
from numpy import *
from scipy import *

In [101]:
tracks_with_tags=load("tracks_with_tags.npy")
tracks_with_tags


array([[2972914,   54087,    1757,    1718,  116712,  189631],
       [2750239,  189631,    3424,  177424,   46208,  205245],
       [1550729,   54087,  109806,   46869,  183258,   54337],
       ..., 
       [2584455,       0,       0,       0,       0,       0],
       [2299706,       0,       0,       0,       0,       0],
       [2739985,       0,       0,       0,       0,       0]])

In [105]:
tag_indexed_byidtrack = zeros((amax(tracks_with_tags[:,0])+1, 5))

transfer = lambda x, y: where(tracks_with_tags[:,0]==x)
    
for x in tracks_with_tags[:,0]:
    i = where(tracks_with_tags[:,0]==x)
    tag_indexed_byidtrack[x] = tracks_with_tags[i,1:]




Ho creato un array che contiene tutti i tag delle canzoni con index l'id: 
tag_indexed_byidtrack[id] = [tags]

sveltirà di molto i calcoli successivi

In [81]:
playlists_with_tracks=load("playlists_with_tracks.npy")
playlists_with_tracks

array([[10024884,  2879006,  1532328, ...,        0,        0,        0],
       [10624787,  2090319,  2152295, ...,        0,        0,        0],
       [ 4891851,  2621486,  2895498, ...,        0,        0,        0],
       ..., 
       [11369546,   416692,  1587449, ...,        0,        0,        0],
       [ 7939535,  2788577,  3090083, ...,        0,        0,        0],
       [  297021,  2789282,  2154608, ...,        0,        0,        0]], dtype=int64)

In [82]:
tracklist_by_playlist = delete(playlists_with_tracks, 0, 1)
tracklist_by_playlist

array([[2879006, 1532328, 3027673, ...,       0,       0,       0],
       [2090319, 2152295, 3230559, ...,       0,       0,       0],
       [2621486, 2895498, 1369381, ...,       0,       0,       0],
       ..., 
       [ 416692, 1587449, 1057389, ...,       0,       0,       0],
       [2788577, 3090083, 1609308, ...,       0,       0,       0],
       [2789282, 2154608,  973448, ...,       0,       0,       0]], dtype=int64)

In [83]:
for row in tracklist_by_playlist:
    for x in row:
        el = zeros(193x5)
        

SyntaxError: invalid syntax (<ipython-input-83-e0b8bad2e384>, line 3)